services:
  garnet:
    image: ghcr.io/microsoft/garnet
    ulimits:
      memlock: -1
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - 'garnetdata:/data'
volumes:
  garnetdata: null
